# coding: utf-8

"""
    emily-openapi-spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from private-emily-client.models.update_withdrawals_request_body import UpdateWithdrawalsRequestBody

class TestUpdateWithdrawalsRequestBody(unittest.TestCase):
    """UpdateWithdrawalsRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateWithdrawalsRequestBody:
        """Test UpdateWithdrawalsRequestBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateWithdrawalsRequestBody`
        """
        model = UpdateWithdrawalsRequestBody()
        if include_optional:
            return UpdateWithdrawalsRequestBody(
                withdrawals = [
                    private-emily-client.models.withdrawal_update.WithdrawalUpdate(
                        fulfillment = null, 
                        last_update_block_hash = '', 
                        last_update_height = 0, 
                        request_id = 0, 
                        status = 'pending', 
                        status_message = '', )
                    ]
            )
        else:
            return UpdateWithdrawalsRequestBody(
                withdrawals = [
                    private-emily-client.models.withdrawal_update.WithdrawalUpdate(
                        fulfillment = null, 
                        last_update_block_hash = '', 
                        last_update_height = 0, 
                        request_id = 0, 
                        status = 'pending', 
                        status_message = '', )
                    ],
        )
        """

    def testUpdateWithdrawalsRequestBody(self):
        """Test UpdateWithdrawalsRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
