# coding: utf-8

"""
    emily-openapi-spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from private-emily-client.api.withdrawal_api import WithdrawalApi


class TestWithdrawalApi(unittest.TestCase):
    """WithdrawalApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WithdrawalApi()

    def tearDown(self) -> None:
        pass

    def test_create_withdrawal(self) -> None:
        """Test case for create_withdrawal

        Create withdrawal handler.
        """
        pass

    def test_get_withdrawal(self) -> None:
        """Test case for get_withdrawal

        Get withdrawal handler.
        """
        pass

    def test_get_withdrawals(self) -> None:
        """Test case for get_withdrawals

        Get withdrawals handler.
        """
        pass

    def test_update_withdrawals(self) -> None:
        """Test case for update_withdrawals

        Update withdrawals handler.
        """
        pass


if __name__ == '__main__':
    unittest.main()
