# coding: utf-8

"""
    emily-openapi-spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from private-emily-client.models.update_deposits_response import UpdateDepositsResponse

class TestUpdateDepositsResponse(unittest.TestCase):
    """UpdateDepositsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateDepositsResponse:
        """Test UpdateDepositsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateDepositsResponse`
        """
        model = UpdateDepositsResponse()
        if include_optional:
            return UpdateDepositsResponse(
                deposits = [
                    private-emily-client.models.deposit.Deposit(
                        amount = 0, 
                        bitcoin_tx_output_index = 0, 
                        bitcoin_txid = '', 
                        deposit_script = '', 
                        fulfillment = null, 
                        last_update_block_hash = '', 
                        last_update_height = 0, 
                        parameters = private-emily-client.models.deposit_parameters.DepositParameters(
                            lock_time = 0, 
                            max_fee = 0, ), 
                        recipient = '', 
                        reclaim_script = '', 
                        status = 'pending', 
                        status_message = '', )
                    ]
            )
        else:
            return UpdateDepositsResponse(
                deposits = [
                    private-emily-client.models.deposit.Deposit(
                        amount = 0, 
                        bitcoin_tx_output_index = 0, 
                        bitcoin_txid = '', 
                        deposit_script = '', 
                        fulfillment = null, 
                        last_update_block_hash = '', 
                        last_update_height = 0, 
                        parameters = private-emily-client.models.deposit_parameters.DepositParameters(
                            lock_time = 0, 
                            max_fee = 0, ), 
                        recipient = '', 
                        reclaim_script = '', 
                        status = 'pending', 
                        status_message = '', )
                    ],
        )
        """

    def testUpdateDepositsResponse(self):
        """Test UpdateDepositsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
