# coding: utf-8

"""
    emily-openapi-spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from private-emily-client.models.limits import Limits

class TestLimits(unittest.TestCase):
    """Limits unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Limits:
        """Test Limits
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Limits`
        """
        model = Limits()
        if include_optional:
            return Limits(
                account_caps = {
                    'key' : private-emily-client.models.account_limits.AccountLimits(
                        peg_cap = 0, 
                        per_deposit_cap = 0, 
                        per_deposit_minimum = 0, 
                        per_withdrawal_cap = 0, )
                    },
                peg_cap = 0,
                per_deposit_cap = 0,
                per_deposit_minimum = 0,
                per_withdrawal_cap = 0
            )
        else:
            return Limits(
                account_caps = {
                    'key' : private-emily-client.models.account_limits.AccountLimits(
                        peg_cap = 0, 
                        per_deposit_cap = 0, 
                        per_deposit_minimum = 0, 
                        per_withdrawal_cap = 0, )
                    },
        )
        """

    def testLimits(self):
        """Test Limits"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
