# coding: utf-8

"""
    emily-openapi-spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from private-emily-client.api.cors_api import CORSApi


class TestCORSApi(unittest.TestCase):
    """CORSApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CORSApi()

    def tearDown(self) -> None:
        pass

    def test_chainstate_height_options(self) -> None:
        """Test case for chainstate_height_options

        CORS support
        """
        pass

    def test_chainstate_options(self) -> None:
        """Test case for chainstate_options

        CORS support
        """
        pass

    def test_deposit_options(self) -> None:
        """Test case for deposit_options

        CORS support
        """
        pass

    def test_deposit_recipient_recipient_options(self) -> None:
        """Test case for deposit_recipient_recipient_options

        CORS support
        """
        pass

    def test_deposit_txid_index_options(self) -> None:
        """Test case for deposit_txid_index_options

        CORS support
        """
        pass

    def test_deposit_txid_options(self) -> None:
        """Test case for deposit_txid_options

        CORS support
        """
        pass

    def test_health_options(self) -> None:
        """Test case for health_options

        CORS support
        """
        pass

    def test_limits_account_options(self) -> None:
        """Test case for limits_account_options

        CORS support
        """
        pass

    def test_limits_options(self) -> None:
        """Test case for limits_options

        CORS support
        """
        pass

    def test_withdrawal_id_options(self) -> None:
        """Test case for withdrawal_id_options

        CORS support
        """
        pass

    def test_withdrawal_options(self) -> None:
        """Test case for withdrawal_options

        CORS support
        """
        pass


if __name__ == '__main__':
    unittest.main()
