# coding: utf-8

"""
    emily-openapi-spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from private-emily-client.models.withdrawal import Withdrawal

class TestWithdrawal(unittest.TestCase):
    """Withdrawal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Withdrawal:
        """Test Withdrawal
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Withdrawal`
        """
        model = Withdrawal()
        if include_optional:
            return Withdrawal(
                amount = 0,
                fulfillment = private-emily-client.models.fulfillment.Fulfillment(
                    bitcoin_block_hash = '', 
                    bitcoin_block_height = 0, 
                    bitcoin_tx_index = 0, 
                    bitcoin_txid = '', 
                    btc_fee = 0, 
                    stacks_txid = '', ),
                last_update_block_hash = '',
                last_update_height = 0,
                parameters = private-emily-client.models.withdrawal_parameters.WithdrawalParameters(
                    max_fee = 0, ),
                recipient = '',
                request_id = 0,
                stacks_block_hash = '',
                stacks_block_height = 0,
                status = 'pending',
                status_message = ''
            )
        else:
            return Withdrawal(
                amount = 0,
                last_update_block_hash = '',
                last_update_height = 0,
                parameters = private-emily-client.models.withdrawal_parameters.WithdrawalParameters(
                    max_fee = 0, ),
                recipient = '',
                request_id = 0,
                stacks_block_hash = '',
                stacks_block_height = 0,
                status = 'pending',
                status_message = '',
        )
        """

    def testWithdrawal(self):
        """Test Withdrawal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
