# coding: utf-8

"""
    emily-openapi-spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from private-emily-client.models.create_deposit_request_body import CreateDepositRequestBody

class TestCreateDepositRequestBody(unittest.TestCase):
    """CreateDepositRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateDepositRequestBody:
        """Test CreateDepositRequestBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateDepositRequestBody`
        """
        model = CreateDepositRequestBody()
        if include_optional:
            return CreateDepositRequestBody(
                bitcoin_tx_output_index = 0,
                bitcoin_txid = '',
                deposit_script = '',
                reclaim_script = '',
                transaction_hex = ''
            )
        else:
            return CreateDepositRequestBody(
                bitcoin_tx_output_index = 0,
                bitcoin_txid = '',
                deposit_script = '',
                reclaim_script = '',
                transaction_hex = '',
        )
        """

    def testCreateDepositRequestBody(self):
        """Test CreateDepositRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
