# coding: utf-8

"""
    emily-openapi-spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from private-emily-client.models.get_deposits_for_transaction_response import GetDepositsForTransactionResponse

class TestGetDepositsForTransactionResponse(unittest.TestCase):
    """GetDepositsForTransactionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetDepositsForTransactionResponse:
        """Test GetDepositsForTransactionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetDepositsForTransactionResponse`
        """
        model = GetDepositsForTransactionResponse()
        if include_optional:
            return GetDepositsForTransactionResponse(
                deposits = [
                    private-emily-client.models.deposit.Deposit(
                        amount = 0, 
                        bitcoin_tx_output_index = 0, 
                        bitcoin_txid = '', 
                        deposit_script = '', 
                        fulfillment = null, 
                        last_update_block_hash = '', 
                        last_update_height = 0, 
                        parameters = private-emily-client.models.deposit_parameters.DepositParameters(
                            lock_time = 0, 
                            max_fee = 0, ), 
                        recipient = '', 
                        reclaim_script = '', 
                        status = 'pending', 
                        status_message = '', )
                    ],
                next_token = ''
            )
        else:
            return GetDepositsForTransactionResponse(
                deposits = [
                    private-emily-client.models.deposit.Deposit(
                        amount = 0, 
                        bitcoin_tx_output_index = 0, 
                        bitcoin_txid = '', 
                        deposit_script = '', 
                        fulfillment = null, 
                        last_update_block_hash = '', 
                        last_update_height = 0, 
                        parameters = private-emily-client.models.deposit_parameters.DepositParameters(
                            lock_time = 0, 
                            max_fee = 0, ), 
                        recipient = '', 
                        reclaim_script = '', 
                        status = 'pending', 
                        status_message = '', )
                    ],
        )
        """

    def testGetDepositsForTransactionResponse(self):
        """Test GetDepositsForTransactionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
