# coding: utf-8

"""
    emily-openapi-spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from private-emily-client.api.deposit_api import DepositApi


class TestDepositApi(unittest.TestCase):
    """DepositApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DepositApi()

    def tearDown(self) -> None:
        pass

    def test_create_deposit(self) -> None:
        """Test case for create_deposit

        Create deposit handler.
        """
        pass

    def test_get_deposit(self) -> None:
        """Test case for get_deposit

        Get deposit handler.
        """
        pass

    def test_get_deposits(self) -> None:
        """Test case for get_deposits

        Get deposits handler.
        """
        pass

    def test_get_deposits_for_recipient(self) -> None:
        """Test case for get_deposits_for_recipient

        Get deposits by recipient handler.
        """
        pass

    def test_get_deposits_for_transaction(self) -> None:
        """Test case for get_deposits_for_transaction

        Get deposits for transaction handler.
        """
        pass

    def test_update_deposits(self) -> None:
        """Test case for update_deposits

        Update deposits handler.
        """
        pass


if __name__ == '__main__':
    unittest.main()
