# coding: utf-8

"""
    emily-openapi-spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from private-emily-client.models.deposit_info import DepositInfo

class TestDepositInfo(unittest.TestCase):
    """DepositInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DepositInfo:
        """Test DepositInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DepositInfo`
        """
        model = DepositInfo()
        if include_optional:
            return DepositInfo(
                amount = 0,
                bitcoin_tx_output_index = 0,
                bitcoin_txid = '',
                deposit_script = '',
                last_update_block_hash = '',
                last_update_height = 0,
                recipient = '',
                reclaim_script = '',
                status = 'pending'
            )
        else:
            return DepositInfo(
                amount = 0,
                bitcoin_tx_output_index = 0,
                bitcoin_txid = '',
                deposit_script = '',
                last_update_block_hash = '',
                last_update_height = 0,
                recipient = '',
                reclaim_script = '',
                status = 'pending',
        )
        """

    def testDepositInfo(self):
        """Test DepositInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
