# coding: utf-8

"""
    emily-openapi-spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from private-emily-client.api.limits_api import LimitsApi


class TestLimitsApi(unittest.TestCase):
    """LimitsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LimitsApi()

    def tearDown(self) -> None:
        pass

    def test_get_limits(self) -> None:
        """Test case for get_limits

        Get the global limits.
        """
        pass

    def test_get_limits_for_account(self) -> None:
        """Test case for get_limits_for_account

        Get limits for account handler.
        """
        pass

    def test_set_limits(self) -> None:
        """Test case for set_limits

        Get limits handler.
        """
        pass

    def test_set_limits_for_account(self) -> None:
        """Test case for set_limits_for_account

        Set limits for account handler.
        """
        pass


if __name__ == '__main__':
    unittest.main()
