# coding: utf-8

"""
    emily-openapi-spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from private-emily-client.models.deposit import Deposit

class TestDeposit(unittest.TestCase):
    """Deposit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Deposit:
        """Test Deposit
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Deposit`
        """
        model = Deposit()
        if include_optional:
            return Deposit(
                amount = 0,
                bitcoin_tx_output_index = 0,
                bitcoin_txid = '',
                deposit_script = '',
                fulfillment = private-emily-client.models.fulfillment.Fulfillment(
                    bitcoin_block_hash = '', 
                    bitcoin_block_height = 0, 
                    bitcoin_tx_index = 0, 
                    bitcoin_txid = '', 
                    btc_fee = 0, 
                    stacks_txid = '', ),
                last_update_block_hash = '',
                last_update_height = 0,
                parameters = private-emily-client.models.deposit_parameters.DepositParameters(
                    lock_time = 0, 
                    max_fee = 0, ),
                recipient = '',
                reclaim_script = '',
                status = 'pending',
                status_message = ''
            )
        else:
            return Deposit(
                amount = 0,
                bitcoin_tx_output_index = 0,
                bitcoin_txid = '',
                deposit_script = '',
                last_update_block_hash = '',
                last_update_height = 0,
                parameters = private-emily-client.models.deposit_parameters.DepositParameters(
                    lock_time = 0, 
                    max_fee = 0, ),
                recipient = '',
                reclaim_script = '',
                status = 'pending',
                status_message = '',
        )
        """

    def testDeposit(self):
        """Test Deposit"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
