# coding: utf-8

"""
    emily-openapi-spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from private-emily-client.models.account_limits import AccountLimits

class TestAccountLimits(unittest.TestCase):
    """AccountLimits unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountLimits:
        """Test AccountLimits
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountLimits`
        """
        model = AccountLimits()
        if include_optional:
            return AccountLimits(
                peg_cap = 0,
                per_deposit_cap = 0,
                per_deposit_minimum = 0,
                per_withdrawal_cap = 0
            )
        else:
            return AccountLimits(
        )
        """

    def testAccountLimits(self):
        """Test AccountLimits"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
