# coding: utf-8

"""
    emily-openapi-spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from private-emily-client.models.chainstate import Chainstate

class TestChainstate(unittest.TestCase):
    """Chainstate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Chainstate:
        """Test Chainstate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Chainstate`
        """
        model = Chainstate()
        if include_optional:
            return Chainstate(
                stacks_block_hash = '',
                stacks_block_height = 0
            )
        else:
            return Chainstate(
                stacks_block_hash = '',
                stacks_block_height = 0,
        )
        """

    def testChainstate(self):
        """Test Chainstate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
