/*
 * emily-openapi-spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetDepositsResponse : Response to get deposits request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDepositsResponse {
    /// Deposit infos: deposits with a little less data.
    #[serde(rename = "deposits")]
    pub deposits: Vec<models::DepositInfo>,
    /// Next token for the search.
    #[serde(
        rename = "nextToken",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub next_token: Option<Option<String>>,
}

impl GetDepositsResponse {
    /// Response to get deposits request.
    pub fn new(deposits: Vec<models::DepositInfo>) -> GetDepositsResponse {
        GetDepositsResponse { deposits, next_token: None }
    }
}
