/*
 * emily-openapi-spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetWithdrawalsResponse : Response to get withdrawals request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetWithdrawalsResponse {
    /// Next token for the search.
    #[serde(
        rename = "nextToken",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub next_token: Option<Option<String>>,
    /// Withdrawal infos: withdrawals with a little less data.
    #[serde(rename = "withdrawals")]
    pub withdrawals: Vec<models::WithdrawalInfo>,
}

impl GetWithdrawalsResponse {
    /// Response to get withdrawals request.
    pub fn new(withdrawals: Vec<models::WithdrawalInfo>) -> GetWithdrawalsResponse {
        GetWithdrawalsResponse { next_token: None, withdrawals }
    }
}
