/*
 * emily-openapi-spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HealthData : Struct that represents the current status of the API.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HealthData {
    /// Whether the API is okay.
    #[serde(rename = "is_okay")]
    pub is_okay: bool,
}

impl HealthData {
    /// Struct that represents the current status of the API.
    pub fn new(is_okay: bool) -> HealthData {
        HealthData { is_okay }
    }
}
