version: '3.8'

services:

  # DynamoDB Tables for the Emily API.
  emily-dynamodb:
    image: "amazon/dynamodb-local:latest"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
    ports:
      - "8000:8000"

  # Modifies Emily's CDK template and creates DynamoDB Tables.
  emily-aws-setup:
    build:
      context: ../..
      dockerfile: docker/sbtc/Dockerfile
      target: emily-aws-setup
    depends_on:
      - emily-dynamodb
    environment:
      - DYNAMODB_ENDPOINT=http://emily-dynamodb:8000

  # Runs the Emily server.
  emily-server:
    build:
      context: ../..
      dockerfile: docker/sbtc/Dockerfile
      target: emily-server
    depends_on:
      emily-aws-setup:
        condition: service_completed_successfully
    environment:
      - DYNAMODB_ENDPOINT=http://emily-dynamodb:8000
      - AWS_ACCESS_KEY_ID=xxxxxxxxxxxx
      - AWS_SECRET_ACCESS_KEY=xxxxxxxxxxxx
      - AWS_REGION=us-west-2
      - PORT=3031
    ports:
      - "3031:3031"

  emily-sidecar:
    build:
      context: ../..
      dockerfile: docker/sbtc/emily-sidecar/Dockerfile
      target: emily-sidecar
    restart: on-failure
    ports:
      - "20540:20540"
    environment:
      EMILY_API_KEY: testApiKey
      EMILY_ENDPOINT: http://emily-server:3031
    depends_on:
      - emily-server

  # Runs the sBTC signer.
  signer:
    build:
      context: ../..
      dockerfile: docker/sbtc/Dockerfile
      target: signer
    entrypoint: "/bin/bash -c '/usr/local/bin/signer -c /signer-config.toml --migrate-db'"
    environment:
      RUST_LOG: info
      SIGNER_SIGNER__DB_ENDPOINT: postgresql://postgres:postgres@postgres-1:5432/signer
      SIGNER_SIGNER__PRIVATE_KEY: 41634762d89dfa09133a4a8e9c1378d0161d29cd0a9433b51f1e3d32947a73dc
      SIGNER_SIGNER__P2P__LISTEN_ON: tcp://0.0.0.0:4122
      SIGNER_SIGNER__P2P__SEEDS: tcp://sbtc-signer-2:4122,tcp://sbtc-signer-3:4122

  # Runs the blocklist client.
  blocklist-client:
    build:
      context: ../..
      dockerfile: docker/sbtc/Dockerfile
      target: blocklist-client
    environment:
      BLOCKLIST_CLIENT__SERVER__HOST: 0.0.0.0
      BLOCKLIST_CLIENT__SERVER__PORT: 3032
      BLOCKLIST_CLIENT__RISK_ANALYSIS__API_URL: xxxxx
      BLOCKLIST_CLIENT__RISK_ANALYSIS__API_KEY: xxxxx
    ports:
      - "3032:3032"
    # TODO(TBD): Add the environment variables or cli arguments that configure
    # the blocklist client.
