/*
 * blocklist-openapi-gen
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ErrorResponse : Structure representing an error response This is used to serialize error messages in HTTP responses
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorResponse {
    #[serde(rename = "message")]
    pub message: String,
}

impl ErrorResponse {
    /// Structure representing an error response This is used to serialize error messages in HTTP responses
    pub fn new(message: String) -> ErrorResponse {
        ErrorResponse {
            message,
        }
    }
}

