[package]
name = "sbtc"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "sbtc"
path = "src/main.rs"
required-features = ["cli"]

[package.metadata.cargo-machete]
ignored = ["bitcoincore-rpc-json"]

[features]
default = []
cli = ["dep:clap", "dep:reqwest", "dep:tokio"]
testing = [
    "dep:aws-smithy-http-client",
    "dep:aws-config",
    "dep:aws-sdk-dynamodb",
    "dep:bitcoincore-rpc",
    "dep:bitcoincore-rpc-json",
    "dep:futures",
    "dep:testcontainers",
    "dep:tokio",
    "dep:url",
]
webhooks = ["dep:hex"]

[dependencies]
bitcoin.workspace = true
clarity.workspace = true
rand.workspace = true
secp256k1.workspace = true
serde.workspace = true
serde_json.workspace = true
stacks-common.workspace = true
thiserror.workspace = true

# Optional Dependencies
aws-config = { workspace = true, optional = true }
aws-sdk-dynamodb = { workspace = true, optional = true }
aws-smithy-http-client = { workspace = true, optional = true }
bitcoincore-rpc = { workspace = true, optional = true }
bitcoincore-rpc-json = { workspace = true, optional = true }
clap = { workspace = true, features = ["usage"], optional = true }
futures = { workspace = true, optional = true }
hex = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }
testcontainers = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
url = { workspace = true, optional = true }

[dev-dependencies]
# Add ourself as a dev-dependency with the "testing" feature enabled to
# automatically include testing functionality for debug builds (i.e. dev/test).
# This also ensures that your IDE will recognize feature-gated code as active.
sbtc = { path = ".", features = ["testing"] }

hex.workspace = true 
assert_matches.workspace = true
bitcoincore-rpc.workspace = true
bitcoincore-rpc-json.workspace = true
more-asserts.workspace = true
proptest.workspace = true
test-case.workspace = true

# Inherit lints from the workspace
[lints]
workspace = true
