/*
 * emily-openapi-spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Chainstate : Chainstate.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Chainstate {
    /// Bitcoin block hash.
    #[serde(rename = "bitcoinBlockHash")]
    pub bitcoin_block_hash: String,
    /// Bitcoin block height
    #[serde(rename = "bitcoinBlockHeight")]
    pub bitcoin_block_height: u64,
    /// Stacks block hash at the height.
    #[serde(rename = "stacksBlockHash")]
    pub stacks_block_hash: String,
    /// Stacks block height.
    #[serde(rename = "stacksBlockHeight")]
    pub stacks_block_height: u64,
}

impl Chainstate {
    /// Chainstate.
    pub fn new(
        bitcoin_block_hash: String,
        bitcoin_block_height: u64,
        stacks_block_hash: String,
        stacks_block_height: u64,
    ) -> Chainstate {
        Chainstate {
            bitcoin_block_hash,
            bitcoin_block_height,
            stacks_block_hash,
            stacks_block_height,
        }
    }
}
