# Use Python 3.12 base image
FROM python:3.12-slim

# Set work directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Set environment variables
ENV FLASK_APP=app.py

# Expose the Flask port
EXPOSE 5000

# Run the Flask application
#CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
