/*
 * emily-openapi-spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DepositParameters : Deposit parameters.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DepositParameters {
    /// Bitcoin block height at which the reclaim script becomes executable.
    #[serde(rename = "lockTime")]
    pub lock_time: u32,
    /// Maximum fee the signers are allowed to take from the deposit to facilitate the transaction.
    #[serde(rename = "maxFee")]
    pub max_fee: u64,
}

impl DepositParameters {
    /// Deposit parameters.
    pub fn new(lock_time: u32, max_fee: u64) -> DepositParameters {
        DepositParameters {
            lock_time,
            max_fee,
        }
    }
}

