/*
 * emily-openapi-spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DepositInfo : Reduced version of the Deposit data.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DepositInfo {
    /// Amount of BTC being deposited in satoshis.
    #[serde(rename = "amount")]
    pub amount: u64,
    /// Output index on the bitcoin transaction associated with this specific deposit.
    #[serde(rename = "bitcoinTxOutputIndex")]
    pub bitcoin_tx_output_index: u32,
    /// Bitcoin transaction id.
    #[serde(rename = "bitcoinTxid")]
    pub bitcoin_txid: String,
    /// Raw deposit script binary in hex.
    #[serde(rename = "depositScript")]
    pub deposit_script: String,
    /// The most recent Stacks block hash the API was aware of when the deposit was last updated. If the most recent update is tied to an artifact on the Stacks blockchain then this hash is the Stacks block hash that contains that artifact.
    #[serde(rename = "lastUpdateBlockHash")]
    pub last_update_block_hash: String,
    /// The most recent Stacks block height the API was aware of when the deposit was last updated. If the most recent update is tied to an artifact on the Stacks blockchain then this height is the Stacks block height that contains that artifact.
    #[serde(rename = "lastUpdateHeight")]
    pub last_update_height: u64,
    /// Stacks address to received the deposited sBTC.
    #[serde(rename = "recipient")]
    pub recipient: String,
    /// Raw reclaim script binary in hex.
    #[serde(rename = "reclaimScript")]
    pub reclaim_script: String,
    #[serde(rename = "status")]
    pub status: models::Status,
}

impl DepositInfo {
    /// Reduced version of the Deposit data.
    pub fn new(amount: u64, bitcoin_tx_output_index: u32, bitcoin_txid: String, deposit_script: String, last_update_block_hash: String, last_update_height: u64, recipient: String, reclaim_script: String, status: models::Status) -> DepositInfo {
        DepositInfo {
            amount,
            bitcoin_tx_output_index,
            bitcoin_txid,
            deposit_script,
            last_update_block_hash,
            last_update_height,
            recipient,
            reclaim_script,
            status,
        }
    }
}

