/*
 * emily-openapi-spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Fulfillment : Data about the fulfillment of an sBTC Operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Fulfillment {
    /// Bitcoin block hash of the block that contains the bitcoin transaction that fulfilled this transaction.
    #[serde(rename = "BitcoinBlockHash")]
    pub bitcoin_block_hash: String,
    /// Bitcoin block height of the block that contains the bitcoin transaction that fulfilled this transaction.
    #[serde(rename = "BitcoinBlockHeight")]
    pub bitcoin_block_height: u64,
    /// Bitcoin transaction output index of the Bitcoin transaction that fulfilled the operation that corresponds to the fulfillment of this specific operation.
    #[serde(rename = "BitcoinTxIndex")]
    pub bitcoin_tx_index: u32,
    /// Bitcoin transaction id of the Bitcoin transaction that fulfilled the operation.
    #[serde(rename = "BitcoinTxid")]
    pub bitcoin_txid: String,
    /// Satoshis consumed to fulfill the sBTC operation.
    #[serde(rename = "BtcFee")]
    pub btc_fee: u64,
    /// Stacks transaction Id that fulfilled this operation.
    #[serde(rename = "StacksTxid")]
    pub stacks_txid: String,
}

impl Fulfillment {
    /// Data about the fulfillment of an sBTC Operation.
    pub fn new(
        bitcoin_block_hash: String,
        bitcoin_block_height: u64,
        bitcoin_tx_index: u32,
        bitcoin_txid: String,
        btc_fee: u64,
        stacks_txid: String,
    ) -> Fulfillment {
        Fulfillment {
            bitcoin_block_hash,
            bitcoin_block_height,
            bitcoin_tx_index,
            bitcoin_txid,
            btc_fee,
            stacks_txid,
        }
    }
}
