/*
 * emily-openapi-spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateDepositsRequestBody : Request structure for update deposit request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateDepositsRequestBody {
    /// Bitcoin transaction id.
    #[serde(rename = "deposits")]
    pub deposits: Vec<models::DepositUpdate>,
}

impl UpdateDepositsRequestBody {
    /// Request structure for update deposit request.
    pub fn new(deposits: Vec<models::DepositUpdate>) -> UpdateDepositsRequestBody {
        UpdateDepositsRequestBody {
            deposits,
        }
    }
}

