/*
 * emily-openapi-spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateDepositsResponse : Response to update deposits request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateDepositsResponse {
    /// Deposit infos: deposits with a little less data.
    #[serde(rename = "deposits")]
    pub deposits: Vec<models::Deposit>,
}

impl UpdateDepositsResponse {
    /// Response to update deposits request.
    pub fn new(deposits: Vec<models::Deposit>) -> UpdateDepositsResponse {
        UpdateDepositsResponse { deposits }
    }
}
