services:
  postgres:
    image: postgres:16.6-bookworm@sha256:c965017e1d29eb03e18a11abc25f5e3cd78cb5ac799d495922264b8489d5a3a1
    stop_grace_period: 5s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: signer
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  sbtc-signer:
    image: blockstack/sbtc:signer-0.0.9-rc6@sha256:44d2c828c6452f75ea2fabe5160ba95a9f944c0fcaeeaea5523dff81da8bc342
    entrypoint: "/bin/bash -c '/usr/local/bin/signer -c /signer-config.toml --migrate-db -o json | tee /logs/sbtc_signer.logs'"
    depends_on:
      - postgres
    environment:
      RUST_LOG: info,signer=debug
    volumes:
      - ./config/signer-config.toml:/signer-config.toml:ro
      - ./logs:/logs
    ports:
      - "4122:4122"
      - "127.0.0.1:8801:8801" # this export is only exposed to the Docker host for security reasons. NEVER expose it to the internet!

  blocklist-client:
    image: blockstack/sbtc:blocklist-client-0.0.9-rc6@sha256:e4fa52ac16c357ae69f3b9eb5d5254a43bc605dbded621291b5637064b04d105
    entrypoint: "/usr/local/bin/blocklist-client"
    ports:
      - "3032:3032"
    environment:
      BLOCKLIST_CLIENT_RISK_ANALYSIS__API_URL: https://public.chainalysis.com
      BLOCKLIST_CLIENT_RISK_ANALYSIS__API_KEY: ${BLOCKLIST_CLIENT_RISK_ANALYSIS__API_KEY}
      BLOCKLIST_CLIENT_SERVER__HOST: "0.0.0.0"
      BLOCKLIST_CLIENT_SERVER__PORT: "3032"

  vector:
    container_name: vector
    image: timberio/vector:0.44.0-debian@sha256:e285e1543366ac306f3957c25d3aca4d2f86855ae274fa4de3522676d72fa0df
    volumes:
      - ./logs:/logs
      - ./vector/vector.yaml:/etc/vector/vector.yaml:ro
    environment:
      STREAM_NAME: ${STREAM_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      VECTOR_LOG: INFO
