name: Cargo Vet
on: [push]

concurrency:
  # limit concurrency of entire workflow runs for a specific branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  cargo-vet:
    name: Run cargo vet
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Install Cargo Vet
        run: cargo install --locked cargo-vet

      - name: Run cargo vet
        run: cargo vet
