name: Contract tests
on: [push]

concurrency:
  # limit concurrency of entire workflow runs for a specific branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  contract_tests:
    name: Contract tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 #v4.0

      - name: Set Node Version
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af #v4.1.0
        with:
          node-version: 22.1.0
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
        working-directory: ./contracts
      - name: Type checks
        run: pnpm typecheck
        working-directory: ./contracts
      - name: Tests
        run: pnpm test
        working-directory: ./contracts
      - name: Lint
        run: pnpm lint
        working-directory: ./contracts
      - name: Generate contract docs and types
        run: pnpm build
        working-directory: ./contracts
      - name: Ensure git is clean
        id: gitStatus
        run: git diff --no-ext-diff --exit-code
        continue-on-error: true
      - name: Error message if git is dirty
        if: steps.gitStatus.outcome == 'failure'
        run: |
          echo "::error::Git is dirty. Make sure you ran \`make build\` before pushing."
          exit 1
