[package]
name = "blocklist-openapi-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
blocklist-client.workspace = true
serde_json.workspace = true
utoipa.workspace = true

[build-dependencies]
blocklist-client.workspace = true
serde_json.workspace = true
utoipa.workspace = true
